In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
train_df = pd.read_csv("/Users/ankitsanjyal/Desktop/Projects/Github/IncomeClassification/output/train.csv")
test_df = pd.read_csv('/Users/ankitsanjyal/Desktop/Projects/Github/IncomeClassification/output/test.csv')

In [8]:
X = train_df.drop('income',axis=1)
y = train_df['income']

X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.1,random_state=42)


In [16]:
X_test = test_df.drop('income',axis=1)
y_test = test_df['income']


In [ ]:
# Import required libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np


# Initialize the AdaBoost Classifier
adaboost = AdaBoostClassifier(n_estimators=100, random_state=42)

# Train the model
adaboost.fit(X_train, y_train)

# Make predictions
y_pred = adaboost.predict(X_val)

# Generate the classification report
print("Classification Report:\n")
print(classification_report(y_val, y_pred))

# Generate the confusion matrix
print("Confusion Matrix:\n")
print(confusion_matrix(y_val, y_pred))


/Users/ankitsanjyal/Library/Python/3.9/lib/python/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Classification Report:

              precision    recall  f1-score   support

         0.0       0.88      0.93      0.90      2456
         1.0       0.74      0.59      0.66       801

    accuracy                           0.85      3257
   macro avg       0.81      0.76      0.78      3257
weighted avg       0.84      0.85      0.84      3257

Confusion Matrix:

[[2287  169]
 [ 326  475]]


In [15]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Define the base model (weak learner)
estimator = DecisionTreeClassifier(random_state=42)

# Define the parameter grid for hyperparameter tuning
param_grid = {
    'n_estimators': [50, 100, 150],               # Number of weak learners
    'learning_rate': [0.01, 0.1, 1.0],           # Learning rate
    'estimator__max_depth': [1, 2, 3],           # Depth of the weak learners
    'estimator__min_samples_split': [2, 5, 10],  # Minimum samples for a split
}

# Initialize the AdaBoost Classifier with a Decision Tree as the base estimator
adaboost = AdaBoostClassifier(estimator=estimator, random_state=42)

# Set up the GridSearchCV
grid_search = GridSearchCV(
    estimator=adaboost,
    param_grid=param_grid,
    cv=5,  # 5-fold cross-validation
    scoring='accuracy',  # Use accuracy for evaluation
    n_jobs=-1,  # Use all available processors
    verbose=1  # Display progress
)

# Fit the model with hyperparameter tuning
grid_search.fit(X_train, y_train)

# Get the best parameters and best model
print("Best Hyperparameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_

# Make predictions with the best model
y_pred = best_model.predict(X_val)

# Evaluate the model
print("Classification Report:\n")
print(classification_report(y_val, y_pred))

print("Confusion Matrix:\n")
print(confusion_matrix(y_val, y_pred))


Fitting 5 folds for each of 81 candidates, totalling 405 fits


/Users/ankitsanjyal/Library/Python/3.9/lib/python/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/Users/ankitsanjyal/Library/Python/3.9/lib/python/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/Users/ankitsanjyal/Library/Python/3.9/lib/python/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/Users/ankitsanjyal/Library/Python/3.9/lib/python/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.

Best Hyperparameters: {'estimator__max_depth': 2, 'estimator__min_samples_split': 2, 'learning_rate': 1.0, 'n_estimators': 50}
Classification Report:

              precision    recall  f1-score   support

         0.0       0.88      0.93      0.90      2456
         1.0       0.73      0.61      0.67       801

    accuracy                           0.85      3257
   macro avg       0.80      0.77      0.78      3257
weighted avg       0.84      0.85      0.84      3257

Confusion Matrix:

[[2272  184]
 [ 309  492]]


In [18]:
y_pred = best_model.predict(X_test)

# Evaluate the model
print("Classification Report test:\n")
print(classification_report(y_test, y_pred))

print("Confusion Matrix test:\n")
print(confusion_matrix(y_test, y_pred))


Classification Report test:

              precision    recall  f1-score   support

         0.0       0.86      0.89      0.87     12435
         1.0       0.59      0.51      0.55      3846

    accuracy                           0.80     16281
   macro avg       0.72      0.70      0.71     16281
weighted avg       0.79      0.80      0.80     16281

Confusion Matrix test:

[[11061  1374]
 [ 1875  1971]]
